require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Naming/FileName:
  Exclude:
    - lib/bp3-hello-engine.rb

Style/Documentation:
  Enabled: false

#Style/StringLiterals:
#  Enabled: true
#  EnforcedStyle: double_quotes
#
#Style/StringLiteralsInInterpolation:
#  Enabled: true
#  EnforcedStyle: double_quotes
#
#Layout/LineLength:
#  Max: 120
